---
- name: Install Java on Debian OS family
  apt: pkg={{ item.package }} 
       update_cache=yes 
       state=latest
  with_items: riemann_packages
  tags:
   - deps

- name: Get {{ riemann_deb }} on Debian OS family
  get_url: url={{ riemann_deb }}
           dest=/tmp
  register: riemann_pkg

- name: Install Riemann on Debian OS family
  apt: deb={{ riemann_pkg.dest }}
       state=installed
       update_cache=yes
