---
- name: install deps
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - ruby
    - ruby-dev
    - build-essential
    - libxml2
    - libxml2-dev

- name: install gem
  shell: 'sudo gem install riemann-tools'

- name: install confs
  template: >
        src={{ riemann_tools_upstart_template }}
        dest=/etc/init/{{ riemann_tools_upstart_name }}.conf
        mode=0644

- name: "start {{ riemann_tools_upstart_name }}"
  service: name={{ riemann_tools_upstart_name }}
           state=restarted
           enabled=yes
